# AndroidIDE Mobile Optimization
org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:MaxMetaspaceSize=384m
org.gradle.daemon=false
org.gradle.configureondemand=true
org.gradle.parallel=false
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true
